### PR TITLE
Add new_proj

### PR DESCRIPTION
**Pull request by ebenp**
Added a create_project function. Please test locally, locally in the office, on Citrix remotely and in the office and on Linux.

Including @jzadra

### CODE REVIEW

**Comment by ebenp** [comment]
Should probably refactor this into separate functions and merge with the existing file create functions before merge.

**Comment by ebenp** [comment]
@jzadra  This is ready for your review

**Comment by ebenp** [comment]
Hidden files in inst are not copied (.gitignore). Will have to decide on a name to copy them across

**Comment by ebenp** [comment]
Fixed .gitignore copy issues
Should add copy failure for folder warnings

**Comment by ebenp** [comment]
Some oddness with overwriting Rproj files

**Comment by kheal** [comment]
I tested ic_new_proj() locally and on Linux box, works great.  I thought we decided to make the default NOT make an renv during this.  I'd like that default to change.  

integral::ic_news() throws this: there is no package called ‘commonmark’.

integral::ic_new_python_file(), integral::ic_new_r_file().  I suggest changing the Purpose:  and History sections of the template to empty or more generalized (similar to what is called in the ic_new_rmd_file().  If not, we're going to end up with 1000 scripts with the same purpose.  

integral::ic_new_rmd_file(), I suggest forgoing an output default.  I think folks who will use .rmd should be able to set their own outputs.

**Comment by ebenp** [comment]
Thanks! These are great suggestions. I'll integrate them in.
Eben

Eben Pendleton (he/him/his) | Project Scientist
Tel: 207.800.3808
45 Exchange Street, Suite 200 | Portland | ME 04101
***@***.*** | www.integral-corp.com

[cid:integral-logo_bb8ba854-3124-462b-8a66-06670ee4325c.jpg]

**Comment by ebenp** [comment]
Updated templates and couldn't recreate ic_news error locally.

**Pull request merged**
